Change the default font family to Arial
itskarelleh/taino-language-app pull request #89
Opened 2024-11-22 00:20 UTC by LinhNguyen2901

2024-11-22 18:51 UTC, itskarelleh requested changes
Do a Google search on adding fallback font family to Expo + React Native.

We don't want to change the default font we just simply want to have a second font family in case the user does not have this one installed on their device.

2024-11-24 04:48 UTC, LinhNguyen2901 commented
I have fixed it to add Arial as the fallback font instead of changing the default font.

2024-11-24 13:27 UTC, itskarelleh commented on lesson-authoring/package.json
I'm not sure this file was modified for this PR

2024-11-24 13:44 UTC, merged

2024-11-24 13:49 UTC, itskarelleh commented
@LinhNguyen2901 Your commit had a lot of changes to the config files which I had to delete but also deleted them on the main branch. So I reverted the changes.